"""Step 6 (part) - the payment-run authorisation pack.

Renders the scored result into:
  * a Markdown authorisation pack (human-readable, with sign-off table)
  * a JSON authorisation pack (machine-readable)
  * a per-payment status CSV
"""
from __future__ import annotations

import datetime as _dt
from typing import List

import pandas as pd

from . import config
from .schema import STATUS_CLEAR, STATUS_HOLD, STATUS_REVIEW, VIOLATION_LABELS

_STATUS_EMOJI = {
    STATUS_CLEAR: "\U0001F7E2",   # green circle
    STATUS_REVIEW: "\U0001F7E1",  # yellow circle
    STATUS_HOLD: "\U0001F534",    # red circle
}


def _money(v) -> str:
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return ""
    return f"{config.CURRENCY_SYMBOL}{float(v):,.2f}"


def build_markdown_pack(score: dict, status_df: pd.DataFrame, narrative: str,
                        batch_id: str = "payment-batch") -> str:
    now = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines: List[str] = []
    lines.append(f"# Payment Run Authorisation Pack")
    lines.append("")
    lines.append(f"**Batch:** {batch_id}  ")
    lines.append(f"**Generated:** {now}  ")
    lines.append(f"**Decision:** {score['decision']}  ")
    lines.append(f"**Batch integrity score:** {score['integrity_score']}/100")
    lines.append("")

    # ---- Controller narrative ----
    lines.append("## Controller narrative")
    lines.append("")
    lines.append(narrative)
    lines.append("")

    # ---- Executive summary ----
    lines.append("## Executive summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| Payments in batch | {score['payment_count']} |")
    lines.append(f"| Total batch value | {_money(score['total_value'])} |")
    lines.append(f"| Clear | {score['clear_count']} |")
    lines.append(f"| Review required | {score['review_count']} |")
    lines.append(f"| Hold | {score['hold_count']} |")
    lines.append(f"| Flagged value | {_money(score['flagged_value'])} |")
    lines.append(f"| High-risk exposure (on hold) | {_money(score['hold_value'])} |")
    lines.append(f"| Red flags | {score['red_flags']} |")
    lines.append(f"| Yellow flags | {score['yellow_flags']} |")
    lines.append("")

    # ---- Flag summary by type ----
    lines.append("## Flags by type")
    lines.append("")
    counts = score.get("counts_by_type", {})
    if counts:
        lines.append("| Flag | Count | Value |")
        lines.append("| --- | --- | --- |")
        for vtype, info in sorted(counts.items(), key=lambda kv: -kv[1]["count"]):
            label = VIOLATION_LABELS.get(vtype, vtype)
            lines.append(f"| {label} | {info['count']} | {_money(info['value'])} |")
    else:
        lines.append("_No flags raised._")
    lines.append("")

    # ---- Payment-by-payment listing ----
    lines.append("## Payment listing")
    lines.append("")
    lines.append("| Payment | Vendor | Invoice | Amount | Status | Flags |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for _, r in status_df.iterrows():
        emoji = _STATUS_EMOJI.get(r["status"], "")
        lines.append(
            f"| {r['payment_id']} | {r.get('vendor_name') or ''} "
            f"| {r.get('invoice_number') or ''} | {_money(r.get('amount'))} "
            f"| {emoji} {r['status']} | {r['flags'] or '-'} |"
        )
    lines.append("")

    # ---- Sign-off table ----
    lines.append("## Digital sign-off")
    lines.append("")
    lines.append("| Role | Name | Decision | Signature | Date |")
    lines.append("| --- | --- | --- | --- | --- |")
    lines.append("| Prepared by (AP) |  |  |  |  |")
    lines.append("| Reviewed by (Controller) |  |  |  |  |")
    lines.append("| Authorised by (CFO) |  |  |  |  |")
    lines.append("")
    lines.append(
        "> Generated by the Pre-Payment Validation Agent. The LLM narrative is "
        "produced from de-identified aggregate metadata only."
    )
    lines.append("")
    return "\n".join(lines)


def build_json_pack(score: dict, status_df: pd.DataFrame, violations: List[dict],
                    narrative: str, metadata: dict,
                    batch_id: str = "payment-batch") -> dict:
    return {
        "batch_id": batch_id,
        "generated_at": _dt.datetime.now().isoformat(timespec="seconds"),
        "decision": score["decision"],
        "integrity_score": score["integrity_score"],
        "summary": {
            "payment_count": score["payment_count"],
            "total_value": score["total_value"],
            "clear_count": score["clear_count"],
            "review_count": score["review_count"],
            "hold_count": score["hold_count"],
            "flagged_value": score["flagged_value"],
            "hold_value": score["hold_value"],
            "red_flags": score["red_flags"],
            "yellow_flags": score["yellow_flags"],
        },
        "flags_by_type": score.get("counts_by_type", {}),
        "cfo_narrative": narrative,
        "narrative_metadata": metadata,
        "payments": status_df.to_dict(orient="records"),
        "violations": violations,
    }
